# Generated by Django 5.1.7 on 2025-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='', max_length=30)),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=20)),
                ('writer', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
